In [1]:
import numpy as np
import pandas as pd
import csv

In [2]:
df2018=pd.read_csv('2018neuron_kw.csv')
df2017=pd.read_csv('2017neuron_kw.csv')
df2016=pd.read_csv('2016neuron_kw.csv')

In [5]:
#添加列索引名称
df2018.columns=['kw','num_kw','No.','info']
df2018[:5]

             kw  num_kw  No.         info
0   hippocampus      21    1  neuron 2018
1  optogenetics      18    2  neuron 2018
2    Drosophila      18    3  neuron 2018
3          fMRI      13    4  neuron 2018
4        memory      13    5  neuron 2018

In [4]:
df2017.columns=['kw','num_kw','No.','info']
df2017[:5]

                  kw  num_kw  No.         info
0        hippocampus      32    1  neuron 2017
1       optogenetics      15    2  neuron 2017
2         plasticity      12    3  neuron 2017
3  electrophysiology      11    4  neuron 2017
4           dopamine      11    5  neuron 2017

In [6]:
df2016.columns=['kw','num_kw','No.','info']
df2016[:5]

                 kw  num_kw  No.         info
0       interneuron       7    1  neuron 2016
1     C.\xa0elegans       5    2  neuron 2016
2               tau       4    3  neuron 2016
3      optogenetics       4    4  neuron 2016
4  axonal transport       4    5  neuron 2016

In [7]:
#2018、2017即df_1817两年的数据进行合并
df_1817=pd.merge(df2018,df2017,how='outer',on='kw')
df_1817[:5]

             kw  num_kw_x  No._x       info_x  num_kw_y  No._y       info_y
0   hippocampus      21.0    1.0  neuron 2018      32.0    1.0  neuron 2017
1  optogenetics      18.0    2.0  neuron 2018      15.0    2.0  neuron 2017
2    Drosophila      18.0    3.0  neuron 2018       7.0   13.0  neuron 2017
3          fMRI      13.0    4.0  neuron 2018       3.0   70.0  neuron 2017
4        memory      13.0    5.0  neuron 2018       9.0    8.0  neuron 2017

In [8]:
#df_1817再和16年的数据合并，得到df_181716三年的数据和
df_181716=pd.merge(df_1817,df2016,how='outer',on='kw')
df_181716[:5]

,kw,num_kw_x,No._x,info_x,num_kw_y,No._y,info_y,num_kw,No.,info
0,hippocampus,21.0,1.0,neuron 2018,32.0,1.0,neuron 2017,3.0,10.0,neuron 2016
1,optogenetics,18.0,2.0,neuron 2018,15.0,2.0,neuron 2017,4.0,4.0,neuron 2016
2,Drosophila,18.0,3.0,neuron 2018,7.0,13.0,neuron 2017,2.0,22.0,neuron 2016
3,fMRI,13.0,4.0,neuron 2018,3.0,70.0,neuron 2017,2.0,38.0,neuron 2016
4,memory,13.0,5.0,neuron 2018,9.0,8.0,neuron 2017,3.0,17.0,neuron 2016

In [9]:
#将索引命名为new_index
df_181716.index.name='new_index'
df_181716[:5]

,kw,num_kw_x,No._x,info_x,num_kw_y,No._y,info_y,num_kw,No.,info
new_index,,,,,,,,,,
0,hippocampus,21.0,1.0,neuron 2018,32.0,1.0,neuron 2017,3.0,10.0,neuron 2016
1,optogenetics,18.0,2.0,neuron 2018,15.0,2.0,neuron 2017,4.0,4.0,neuron 2016
2,Drosophila,18.0,3.0,neuron 2018,7.0,13.0,neuron 2017,2.0,22.0,neuron 2016
3,fMRI,13.0,4.0,neuron 2018,3.0,70.0,neuron 2017,2.0,38.0,neuron 2016
4,memory,13.0,5.0,neuron 2018,9.0,8.0,neuron 2017,3.0,17.0,neuron 2016

In [10]:
#对总表的索引列进行重命名
df_181716.columns=['kw','num_kw2018','No._2018','info_2018','num_kw2017','No._2017','info_2017',
                   'num_kw2016','No._2016','info_2016']
df_181716[:5]

,kw,num_kw2018,No._2018,info_2018,num_kw2017,No._2017,info_2017,num_kw2016,No._2016,info_2016
new_index,,,,,,,,,,
0,hippocampus,21.0,1.0,neuron 2018,32.0,1.0,neuron 2017,3.0,10.0,neuron 2016
1,optogenetics,18.0,2.0,neuron 2018,15.0,2.0,neuron 2017,4.0,4.0,neuron 2016
2,Drosophila,18.0,3.0,neuron 2018,7.0,13.0,neuron 2017,2.0,22.0,neuron 2016
3,fMRI,13.0,4.0,neuron 2018,3.0,70.0,neuron 2017,2.0,38.0,neuron 2016
4,memory,13.0,5.0,neuron 2018,9.0,8.0,neuron 2017,3.0,17.0,neuron 2016

In [11]:
#数据透视化，移除非数值NaN，即将NaN转化为0
df_value=pd.pivot_table(df_181716,index=['new_index','kw'],values=['num_kw2018','num_kw2017','num_kw2016'],fill_value=0)
df_value[:5]

                        num_kw2016  num_kw2017  num_kw2018
new_index kw
0         hippocampus            3          32          21
1         optogenetics           4          15          18
2         Drosophila             2           7          18
3         fMRI                   2           3          13
4         memory                 3           9          13

In [12]:
#数据求和
df_value['sum_num_kw']=df_value['num_kw2016'] + df_value['num_kw2017'] + df_value['num_kw2018']
df_value[:5]

                        num_kw2016  num_kw2017  num_kw2018  sum_num_kw
new_index kw
0         hippocampus            3          32          21          56
1         optogenetics           4          15          18          37
2         Drosophila             2           7          18          27
3         fMRI                   2           3          13          18
4         memory                 3           9          13          25

In [13]:
#降序排列
df_final=df_value.sort_values('sum_num_kw',ascending=False)
df_final[:100]

,,num_kw2016,num_kw2017,num_kw2018,sum_num_kw
new_index,kw,,,,
0,hippocampus,3,32,21,56
1,optogenetics,4,15,18,37
2,Drosophila,2,7,18,27
4,memory,3,9,13,25
6,synapse,1,10,11,22
9,dopamine,1,11,10,22
5,learning,2,8,11,21
17,plasticity,1,12,7,20
3,fMRI,2,3,13,18
8,prefrontal cortex,3,5,10,18
26,interneuron,7,4,6,17
22,electrophysiology,0,11,6,17
24,reward,4,6,6,16
7,attention,2,3,10,15
43,synaptic transmission,1,8,5,14
14,synaptic plasticity,3,4,7,14
16,development,0,7,7,14
66,GABA,2,8,4,14
19,calcium imaging,1,6,6,13
51,C.\xa0elegans,5,3,4,12
72,cortex,0,9,3,12
35,neurodegeneration,1,6,5,12
42,visual cortex,1,6,5,12
12,basal ganglia,0,5,7,12
10,neuromodulation,1,1,9,11
11,mouse,0,3,8,11
44,amygdala,2,4,5,11
23,oscillations,1,3,6,10
18,microglia,0,4,6,10
63,olfaction,0,6,4,10
...,...,...,...,...,...
253,cytoskeleton,2,3,2,7
58,decision-making,1,2,4,7
269,axonal transport,4,1,2,7
45,arousal,0,3,4,7
98,motor learning,0,3,3,6
97,Parkinson’s disease,0,3,3,6
301,axon guidance,1,3,2,6
250,pattern separation,0,4,2,6
114,CA1,1,3,2,6
234,two-photon imaging,0,4,2,6
220,tau,4,0,2,6
281,posterior parietal cortex,0,4,2,6
88,parvalbumin,2,1,3,6
508,LTP,0,5,1,6
672,Drosophila melanogaster,0,5,1,6
64,active zone,0,2,4,6
61,ventral tegmental area,1,1,4,6
62,sleep,0,2,4,6
25,connectivity,0,0,6,6
57,pain,0,2,4,6
54,oscillation,1,1,4,6
48,behavior,0,2,4,6
151,neurogenesis,0,4,2,6
28,mushroom body,0,1,5,6
67,human,1,1,4,6
33,auditory,0,1,5,6
86,ALS,0,2,3,5
1579,microtubule,3,2,0,5
53,medial prefrontal cortex,0,1,4,5
29,V4,0,0,5,5

In [14]:
#保存数据
df_final.to_csv('neuron_sum.csv')